import { getProvider } from "../providers/index.js";
import { defaultAgent } from "../config.js";

const NAMING_PROMPT = `Generate a 3-5 word title summarizing the topic of a conversation that begins with the user message below. Reply with ONLY the title — no quotes, no punctuation, no preamble.

User message:
`;

// Fallback when the default agent is unavailable or fails.
function fallback(prompt: string): string {
  const words = prompt.trim().split(/\s+/).slice(0, 5).join(" ");
  return words.slice(0, 60) || "untitled";
}

const RENAME_PROMPT = `Re-summarize the following conversation transcript with a fresh 3-5 word title that reflects what it's actually about. Reply with ONLY the title — no quotes, no punctuation, no preamble.

Transcript:
`;

// Generate a title from an existing conversation transcript (used by /rename).
export async function generateNameFromTranscript(transcript: string): Promise<string> {
  const agent = defaultAgent();
  try {
    const provider = getProvider(agent);
    const handle = provider.run({
      prompt: RENAME_PROMPT + transcript,
      yolo: true,
      internal: true,
    });
    for await (const _ of handle.events) {
      /* drain */
    }
    const meta = await handle.done;
    if (meta.status !== "completed" || !meta.output) return "untitled";
    return (
      meta.output.trim().replace(/^["']|["']$/g, "").slice(0, 80) || "untitled"
    );
  } catch {
    return "untitled";
  }
}

// Returns a short title generated by the default AI agent. Best-effort: any
// failure falls back to a truncated form of the user prompt.
export async function generateName(prompt: string): Promise<string> {
  const agent = defaultAgent();
  try {
    const provider = getProvider(agent);
    const handle = provider.run({
      prompt: NAMING_PROMPT + prompt,
      yolo: true,
      internal: true,
    });
    // Drain events; we only need the final output.
    for await (const _ of handle.events) {
      /* discard */
    }
    const meta = await handle.done;
    if (meta.status !== "completed" || !meta.output) return fallback(prompt);
    return meta.output.trim().replace(/^["']|["']$/g, "").slice(0, 80) || fallback(prompt);
  } catch {
    return fallback(prompt);
  }
}
